import { GlossaryTermLayout } from "@/components/resources/GlossaryTermLayout";

const PipelineTerm = () => {
  return (
    <GlossaryTermLayout
      term="Pipeline"
      category="Sales & RevOps"
      quickDefinition="Visual representation of all active sales opportunities organized by stage (discovery, demo, proposal, negotiation), showing projected revenue and probability of close."
      fullDefinition={[
        "Sales Pipeline visualizes where all active deals sit in the sales process, typically shown as funnel with stages: Lead→ MQL→SQL→Discovery Call→Demo→Proposal→Negotiation→Closed Won. Each stage has: number of opportunities, total deal value, average deal size, conversion rate to next stage, and average time in stage. Pipeline health determines whether company will hit revenue targets.",
        "Healthy pipeline has 3-5× coverage of revenue target (if quota is $1M, pipeline should have $3-5M in opportunities accounting for deals that won't close). Pipeline velocity measures how quickly deals move through stages—stalled deals indicate problems with qualification, product fit, or pricing. Stage-by-stage conversion rates reveal bottlenecks.",
        "Pipeline attribution connects marketing campaigns (via UTM tracking) to deals in pipeline, measuring marketing's contribution to revenue. Which UTM sources generate opportunities? What's average deal size by source? How long from first touch to closed-won by channel? This data drives marketing budget allocation based on revenue impact, not just lead volume.",
        "Common pipeline metrics include: total pipeline value, weighted pipeline (deal value × probability), pipeline coverage ratio (pipeline ÷ quota), average deal size, average sales cycle length, stage conversion rates, and win rate. Tracking these by original UTM source/campaign enables true marketing ROI measurement."
      ]}
      whenToUse="Use pipeline analysis when forecasting revenue, identifying sales process bottlenecks, measuring marketing contribution to revenue, optimizing sales team capacity, diagnosing why deals stall, or allocating marketing budget based on pipeline generation rather than lead volume."
      whenNotToUse="Don't rely solely on pipeline for revenue forecasting (deals slip, forecasts change), use pipeline metrics for self-serve products without sales involvement, or compare pipeline across different sales cycle lengths without normalization."
      commonMistakes={[
        "Not connecting pipeline opportunities to original UTM source (can't measure marketing ROI)",
        "Sales team inflating opportunity values to hit pipeline coverage ratios (garbage forecasting)",
        "Not tracking pipeline velocity—deals stuck in stages for months indicate qualification problems",
        "Marketing optimizing for MQL volume without measuring MQL→Pipeline→Revenue conversion",
        "Comparing absolute pipeline values across different deal sizes (enterprise vs SMB)"
      ]}
      goodExamples={[
        "Dashboard showing pipeline generated by UTM campaign with average deal size and close rate",
        "Weekly pipeline review highlighting deals stuck in same stage for 30+ days",
        "Analysis proving webinars generate 50% fewer SQLs but 2× higher average deal value",
        "Marketing budget allocation based on cost-per-pipeline-dollar by channel, not just cost-per-lead"
      ]}
      badExamples={[
        "Celebrating 500 MQLs without tracking how many become pipeline opportunities",
        "Not connecting CRM opportunities to original marketing UTM source (attribution gap)",
        "Accepting $10M pipeline at face value without weighting by probability (inflated forecast)",
        "Marketing measuring success by MQL volume when only 2% of MQLs enter pipeline"
      ]}
      relatedTerms={[
        { slug: "mql", term: "MQL (Marketing Qualified Lead)", category: "Sales & RevOps" },
        { slug: "sql", term: "SQL (Sales Qualified Lead)", category: "Sales & RevOps" },
        { slug: "conversion-rate", term: "Conversion Rate", category: "Sales & RevOps" },
        { slug: "arr", term: "ARR (Annual Recurring Revenue)", category: "B2B SaaS" },
        { slug: "utm", term: "UTM", category: "Core Tracking" }
      ]}
      relatedResources={[
        { title: "Attribution Clarity Framework", url: "/resources/frameworks/attribution-clarity", type: "framework" },
        { title: "Growth Analytics Guide", url: "/resources/guides/growth-analytics", type: "guide" },
        { title: "Startup Analytics Playbook", url: "/resources/playbooks/startup-analytics", type: "playbook" }
      ]}
    />
  );
};

export default PipelineTerm;
