import { useState } from "react";
import { Button } from "@/components/ui/button";
import { RadioGroup, RadioGroupItem } from "@/components/ui/radio-group";
import { Label } from "@/components/ui/label";
import { Download } from "lucide-react";
import { toast } from "sonner";

const questions = [
  {
    dimension: "Naming Conventions",
    questions: [
      {
        id: "nc1",
        text: "Do you have documented UTM naming conventions?",
        answers: ["No documentation", "Some guidelines", "Comprehensive docs", "Enforced via tools"]
      },
      {
        id: "nc2",
        text: "How consistently are naming conventions followed?",
        answers: ["Rarely", "Sometimes", "Usually", "Always"]
      },
      {
        id: "nc3",
        text: "How often do you audit UTM consistency?",
        answers: ["Never", "Annually", "Quarterly", "Monthly or more"]
      }
    ]
  },
  {
    dimension: "Template Usage",
    questions: [
      {
        id: "tu1",
        text: "Do you have pre-built UTM templates?",
        answers: ["No templates", "A few basic ones", "Many templates", "Complete library"]
      },
      {
        id: "tu2",
        text: "What percentage of campaigns use templates?",
        answers: ["<25%", "25-50%", "50-75%", ">75%"]
      }
    ]
  },
  {
    dimension: "Team Training",
    questions: [
      {
        id: "tt1",
        text: "Have team members received UTM training?",
        answers: ["No training", "Some informal training", "Formal onboarding", "Regular training sessions"]
      },
      {
        id: "tt2",
        text: "Who can create UTM links?",
        answers: ["Anyone", "Marketing only", "Trained users only", "Centralized team"]
      }
    ]
  },
  {
    dimension: "Tool Enforcement",
    questions: [
      {
        id: "te1",
        text: "What tools enforce UTM standards?",
        answers: ["None", "Spreadsheets", "Basic URL builder", "Dedicated platform"]
      },
      {
        id: "te2",
        text: "How are UTM errors caught?",
        answers: ["After launch", "Manual review", "Automated validation", "Real-time prevention"]
      }
    ]
  },
  {
    dimension: "Reporting & Analytics",
    questions: [
      {
        id: "ra1",
        text: "How often do you review UTM performance?",
        answers: ["Never", "Quarterly", "Monthly", "Weekly"]
      },
      {
        id: "ra2",
        text: "Can you easily compare campaigns?",
        answers: ["Very difficult", "Manual work needed", "Mostly automated", "Fully automated"]
      }
    ]
  }
];

export const GovernanceMaturityAssessment = () => {
  const [answers, setAnswers] = useState<Record<string, number>>({});
  const [showResults, setShowResults] = useState(false);

  const calculateScore = () => {
    const totalQuestions = questions.reduce((sum, dim) => sum + dim.questions.length, 0);
    const totalScore = Object.values(answers).reduce((sum, score) => sum + score, 0);
    return Math.round((totalScore / (totalQuestions * 3)) * 100);
  };

  const getDimensionScore = (dimension: string) => {
    const dimQuestions = questions.find(d => d.dimension === dimension)?.questions || [];
    const dimAnswers = dimQuestions.map(q => answers[q.id] || 0);
    const total = dimAnswers.reduce((sum, score) => sum + score, 0);
    return Math.round((total / (dimQuestions.length * 3)) * 100);
  };

  const handleSubmit = () => {
    if (Object.keys(answers).length < questions.reduce((sum, d) => sum + d.questions.length, 0)) {
      toast.error("Please answer all questions");
      return;
    }
    setShowResults(true);
  };

  const downloadReport = () => {
    const score = calculateScore();
    const report = `UTM Governance Maturity Assessment Report

Overall Score: ${score}/100

Dimension Breakdown:
${questions.map(dim => `- ${dim.dimension}: ${getDimensionScore(dim.dimension)}/100`).join('\n')}

Maturity Level: ${score >= 80 ? "Advanced" : score >= 60 ? "Intermediate" : score >= 40 ? "Basic" : "Beginning"}

Generated by utm.one`;

    const blob = new Blob([report], { type: "text/plain" });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "utm-governance-assessment.txt";
    a.click();
    toast.success("Report downloaded");
  };

  const overallScore = showResults ? calculateScore() : 0;

  return (
    <div className="space-y-6 p-6 bg-card border border-border/50 rounded-xl">
      <div>
        <h4 className="font-semibold text-foreground mb-2">Governance Maturity Assessment</h4>
        <p className="text-sm text-muted-foreground">
          Answer 13 questions to assess your UTM governance maturity (0-100 score)
        </p>
      </div>

      {!showResults ? (
        <div className="space-y-8">
          {questions.map((dimension, dimIndex) => (
            <div key={dimIndex} className="space-y-4">
              <h5 className="text-sm font-semibold text-foreground">{dimension.dimension}</h5>
              {dimension.questions.map((question, qIndex) => (
                <div key={question.id} className="space-y-3 p-4 bg-background rounded-lg border border-border/30">
                  <p className="text-sm text-foreground">{question.text}</p>
                  <RadioGroup
                    value={answers[question.id]?.toString()}
                    onValueChange={(value) => setAnswers({ ...answers, [question.id]: parseInt(value) })}
                  >
                    {question.answers.map((answer, aIndex) => (
                      <div key={aIndex} className="flex items-center space-x-2">
                        <RadioGroupItem value={aIndex.toString()} id={`${question.id}-${aIndex}`} />
                        <Label htmlFor={`${question.id}-${aIndex}`} className="text-sm cursor-pointer">
                          {answer}
                        </Label>
                      </div>
                    ))}
                  </RadioGroup>
                </div>
              ))}
            </div>
          ))}

          <Button onClick={handleSubmit} className="w-full">
            Calculate Maturity Score
          </Button>
        </div>
      ) : (
        <div className="space-y-6">
          {/* Overall Score */}
          <div className="text-center p-8 bg-background rounded-lg border border-border/30">
            <p className="text-sm text-muted-foreground mb-2">Overall Maturity Score</p>
            <div className="flex items-center justify-center gap-3 mb-4">
              <span
                className={`text-6xl font-bold ${
                  overallScore >= 80
                    ? "text-green-500"
                    : overallScore >= 60
                    ? "text-blue-500"
                    : overallScore >= 40
                    ? "text-yellow-500"
                    : "text-red-500"
                }`}
              >
                {overallScore}
              </span>
              <span className="text-2xl text-muted-foreground">/ 100</span>
            </div>
            <p className="text-lg font-semibold text-foreground">
              {overallScore >= 80
                ? "Advanced - Industry Leading"
                : overallScore >= 60
                ? "Intermediate - Good Foundation"
                : overallScore >= 40
                ? "Basic - Needs Improvement"
                : "Beginning - Significant Work Needed"}
            </p>
          </div>

          {/* Dimension Breakdown */}
          <div className="space-y-3">
            <h5 className="text-sm font-semibold text-foreground">Dimension Breakdown</h5>
            {questions.map((dimension, index) => {
              const dimScore = getDimensionScore(dimension.dimension);
              return (
                <div key={index} className="flex items-center justify-between p-3 bg-background rounded-lg border border-border/30">
                  <span className="text-sm text-foreground">{dimension.dimension}</span>
                  <span
                    className={`text-sm font-semibold ${
                      dimScore >= 80
                        ? "text-green-500"
                        : dimScore >= 60
                        ? "text-blue-500"
                        : dimScore >= 40
                        ? "text-yellow-500"
                        : "text-red-500"
                    }`}
                  >
                    {dimScore}/100
                  </span>
                </div>
              );
            })}
          </div>

          {/* Actions */}
          <div className="flex gap-3">
            <Button onClick={() => setShowResults(false)} variant="outline" className="flex-1">
              Retake Assessment
            </Button>
            <Button onClick={downloadReport} className="flex-1">
              <Download className="w-4 h-4 mr-2" />
              Download Report
            </Button>
          </div>
        </div>
      )}
    </div>
  );
};
