-- Add country column to early_access_requests
ALTER TABLE early_access_requests 
ADD COLUMN IF NOT EXISTS country TEXT;

-- Delete existing seed data (keep real users - those without auto-generated referral codes pattern)
DELETE FROM early_access_requests 
WHERE email LIKE '%example.com%' 
   OR email LIKE '%test%'
   OR email LIKE '%seed%';

-- Insert 200+ diverse seed records with Indian (35%), US (30%), European (20%), Other (15%) names
-- Indian names (70 records - 35%)
INSERT INTO early_access_requests (name, email, country, team_size, role, reason_for_joining, status, referral_code, referral_score, created_at) VALUES
('Priya Sharma', 'priya.sharma@example.in', 'India', '11-50', 'marketing', 'UTM tracking', 'approved', 'priya-ref-' || substr(md5(random()::text), 1, 8), 95, now() - interval '15 days'),
('Rahul Gupta', 'rahul.gupta@example.in', 'India', '51-200', 'sales', 'link management', 'pending', 'rahul-ref-' || substr(md5(random()::text), 1, 8), 88, now() - interval '12 days'),
('Arjun Patel', 'arjun.patel@example.in', 'India', '11-50', 'marketing ops', 'analytics', 'pending', 'arjun-ref-' || substr(md5(random()::text), 1, 8), 82, now() - interval '10 days'),
('Ananya Singh', 'ananya.singh@example.in', 'India', '2-10', 'marketing', 'QR codes', 'pending', 'ananya-ref-' || substr(md5(random()::text), 1, 8), 79, now() - interval '8 days'),
('Vikram Reddy', 'vikram.reddy@example.in', 'India', '201-500', 'developer', 'all of the above', 'approved', 'vikram-ref-' || substr(md5(random()::text), 1, 8), 91, now() - interval '14 days'),
('Neha Kapoor', 'neha.kapoor@example.in', 'India', '11-50', 'marketing', 'link management', 'pending', 'neha-ref-' || substr(md5(random()::text), 1, 8), 76, now() - interval '7 days'),
('Rohan Desai', 'rohan.desai@example.in', 'India', '51-200', 'sales', 'UTM tracking', 'pending', 'rohan-ref-' || substr(md5(random()::text), 1, 8), 73, now() - interval '6 days'),
('Kavya Iyer', 'kavya.iyer@example.in', 'India', '2-10', 'marketing', 'analytics', 'pending', 'kavya-ref-' || substr(md5(random()::text), 1, 8), 68, now() - interval '5 days'),
('Aditya Kumar', 'aditya.kumar@example.in', 'India', '11-50', 'developer', 'all of the above', 'pending', 'aditya-ref-' || substr(md5(random()::text), 1, 8), 85, now() - interval '9 days'),
('Shreya Menon', 'shreya.menon@example.in', 'India', '51-200', 'marketing ops', 'team governance', 'approved', 'shreya-ref-' || substr(md5(random()::text), 1, 8), 93, now() - interval '13 days'),
('Karthik Nair', 'karthik.nair@example.in', 'India', '11-50', 'sales', 'link management', 'pending', 'karthik-ref-' || substr(md5(random()::text), 1, 8), 65, now() - interval '4 days'),
('Divya Agarwal', 'divya.agarwal@example.in', 'India', '2-10', 'marketing', 'QR codes', 'pending', 'divya-ref-' || substr(md5(random()::text), 1, 8), 62, now() - interval '3 days'),
('Siddharth Joshi', 'siddharth.joshi@example.in', 'India', '201-500', 'developer', 'analytics', 'pending', 'siddharth-ref-' || substr(md5(random()::text), 1, 8), 80, now() - interval '11 days'),
('Isha Malhotra', 'isha.malhotra@example.in', 'India', '11-50', 'marketing', 'UTM tracking', 'pending', 'isha-ref-' || substr(md5(random()::text), 1, 8), 58, now() - interval '2 days'),
('Aryan Mehta', 'aryan.mehta@example.in', 'India', '51-200', 'sales', 'link management', 'pending', 'aryan-ref-' || substr(md5(random()::text), 1, 8), 71, now() - interval '6 days'),
('Pooja Rao', 'pooja.rao@example.in', 'India', '2-10', 'marketing ops', 'team governance', 'pending', 'pooja-ref-' || substr(md5(random()::text), 1, 8), 55, now() - interval '1 day'),
('Varun Saxena', 'varun.saxena@example.in', 'India', '11-50', 'developer', 'all of the above', 'pending', 'varun-ref-' || substr(md5(random()::text), 1, 8), 67, now() - interval '5 days'),
('Riya Khanna', 'riya.khanna@example.in', 'India', '51-200', 'marketing', 'analytics', 'pending', 'riya-ref-' || substr(md5(random()::text), 1, 8), 74, now() - interval '7 days'),
('Arnav Bose', 'arnav.bose@example.in', 'India', '11-50', 'sales', 'QR codes', 'pending', 'arnav-ref-' || substr(md5(random()::text), 1, 8), 63, now() - interval '4 days'),
('Meera Pillai', 'meera.pillai@example.in', 'India', '2-10', 'marketing', 'UTM tracking', 'pending', 'meera-ref-' || substr(md5(random()::text), 1, 8), 52, now() - interval '1 day'),
('Aarav Chopra', 'aarav.chopra@example.in', 'India', '201-500', 'developer', 'link management', 'approved', 'aarav-ref-' || substr(md5(random()::text), 1, 8), 89, now() - interval '12 days'),
('Diya Ghosh', 'diya.ghosh@example.in', 'India', '11-50', 'marketing ops', 'analytics', 'pending', 'diya-ref-' || substr(md5(random()::text), 1, 8), 69, now() - interval '5 days'),
('Ishaan Verma', 'ishaan.verma@example.in', 'India', '51-200', 'sales', 'team governance', 'pending', 'ishaan-ref-' || substr(md5(random()::text), 1, 8), 60, now() - interval '3 days'),
('Anushka Pandey', 'anushka.pandey@example.in', 'India', '2-10', 'marketing', 'QR codes', 'pending', 'anushka-ref-' || substr(md5(random()::text), 1, 8), 75, now() - interval '8 days'),
('Ayaan Mishra', 'ayaan.mishra@example.in', 'India', '11-50', 'developer', 'all of the above', 'pending', 'ayaan-ref-' || substr(md5(random()::text), 1, 8), 57, now() - interval '2 days'),
('Kiara Shah', 'kiara.shah@example.in', 'India', '51-200', 'marketing', 'UTM tracking', 'pending', 'kiara-ref-' || substr(md5(random()::text), 1, 8), 66, now() - interval '4 days'),
('Reyansh Gupta', 'reyansh.gupta@example.in', 'India', '11-50', 'sales', 'link management', 'pending', 'reyansh-ref-' || substr(md5(random()::text), 1, 8), 53, now() - interval '1 day'),
('Saanvi Patel', 'saanvi.patel@example.in', 'India', '2-10', 'marketing ops', 'analytics', 'pending', 'saanvi-ref-' || substr(md5(random()::text), 1, 8), 70, now() - interval '6 days'),
('Vihaan Singh', 'vihaan.singh@example.in', 'India', '201-500', 'developer', 'team governance', 'pending', 'vihaan-ref-' || substr(md5(random()::text), 1, 8), 78, now() - interval '9 days'),
('Myra Reddy', 'myra.reddy@example.in', 'India', '11-50', 'marketing', 'QR codes', 'approved', 'myra-ref-' || substr(md5(random()::text), 1, 8), 87, now() - interval '11 days'),
('Advait Desai', 'advait.desai@example.in', 'India', '51-200', 'sales', 'all of the above', 'pending', 'advait-ref-' || substr(md5(random()::text), 1, 8), 61, now() - interval '3 days'),
('Aanya Kapoor', 'aanya.kapoor@example.in', 'India', '2-10', 'marketing', 'UTM tracking', 'pending', 'aanya-ref-' || substr(md5(random()::text), 1, 8), 54, now() - interval '1 day'),
('Shivansh Iyer', 'shivansh.iyer@example.in', 'India', '11-50', 'developer', 'link management', 'pending', 'shivansh-ref-' || substr(md5(random()::text), 1, 8), 72, now() - interval '7 days'),
('Aadhya Kumar', 'aadhya.kumar@example.in', 'India', '51-200', 'marketing ops', 'analytics', 'pending', 'aadhya-ref-' || substr(md5(random()::text), 1, 8), 59, now() - interval '2 days'),
('Vivaan Menon', 'vivaan.menon@example.in', 'India', '11-50', 'sales', 'team governance', 'pending', 'vivaan-ref-' || substr(md5(random()::text), 1, 8), 64, now() - interval '4 days'),
('Navya Nair', 'navya.nair@example.in', 'India', '2-10', 'marketing', 'QR codes', 'pending', 'navya-ref-' || substr(md5(random()::text), 1, 8), 56, now() - interval '2 days'),
('Dhruv Agarwal', 'dhruv.agarwal@example.in', 'India', '201-500', 'developer', 'all of the above', 'pending', 'dhruv-ref-' || substr(md5(random()::text), 1, 8), 77, now() - interval '8 days'),
('Pari Joshi', 'pari.joshi@example.in', 'India', '11-50', 'marketing', 'UTM tracking', 'pending', 'pari-ref-' || substr(md5(random()::text), 1, 8), 51, now() - interval '1 day'),
('Atharv Malhotra', 'atharv.malhotra@example.in', 'India', '51-200', 'sales', 'link management', 'pending', 'atharv-ref-' || substr(md5(random()::text), 1, 8), 68, now() - interval '5 days'),
('Anaya Mehta', 'anaya.mehta@example.in', 'India', '2-10', 'marketing ops', 'analytics', 'pending', 'anaya-ref-' || substr(md5(random()::text), 1, 8), 62, now() - interval '3 days'),
('Kabir Rao', 'kabir.rao@example.in', 'India', '11-50', 'developer', 'team governance', 'pending', 'kabir-ref-' || substr(md5(random()::text), 1, 8), 70, now() - interval '6 days'),
('Nitya Saxena', 'nitya.saxena@example.in', 'India', '51-200', 'marketing', 'QR codes', 'pending', 'nitya-ref-' || substr(md5(random()::text), 1, 8), 58, now() - interval '2 days'),
('Shaurya Khanna', 'shaurya.khanna@example.in', 'India', '11-50', 'sales', 'all of the above', 'pending', 'shaurya-ref-' || substr(md5(random()::text), 1, 8), 65, now() - interval '4 days'),
('Ira Bose', 'ira.bose@example.in', 'India', '2-10', 'marketing', 'UTM tracking', 'pending', 'ira-ref-' || substr(md5(random()::text), 1, 8), 53, now() - interval '1 day'),
('Rudra Pillai', 'rudra.pillai@example.in', 'India', '201-500', 'developer', 'link management', 'approved', 'rudra-ref-' || substr(md5(random()::text), 1, 8), 86, now() - interval '10 days'),
('Zara Chopra', 'zara.chopra@example.in', 'India', '11-50', 'marketing ops', 'analytics', 'pending', 'zara-ref-' || substr(md5(random()::text), 1, 8), 60, now() - interval '3 days'),
('Arjun Ghosh', 'arjun.ghosh@example.in', 'India', '51-200', 'sales', 'team governance', 'pending', 'arjun2-ref-' || substr(md5(random()::text), 1, 8), 67, now() - interval '5 days'),
('Myra Verma', 'myra.verma@example.in', 'India', '2-10', 'marketing', 'QR codes', 'pending', 'myra2-ref-' || substr(md5(random()::text), 1, 8), 55, now() - interval '1 day'),
('Vihaan Pandey', 'vihaan.pandey@example.in', 'India', '11-50', 'developer', 'all of the above', 'pending', 'vihaan2-ref-' || substr(md5(random()::text), 1, 8), 71, now() - interval '6 days'),
('Aadhya Mishra', 'aadhya.mishra@example.in', 'India', '51-200', 'marketing', 'UTM tracking', 'pending', 'aadhya2-ref-' || substr(md5(random()::text), 1, 8), 57, now() - interval '2 days'),
('Shivansh Shah', 'shivansh.shah@example.in', 'India', '11-50', 'sales', 'link management', 'pending', 'shivansh2-ref-' || substr(md5(random()::text), 1, 8), 63, now() - interval '4 days'),
('Aanya Gupta', 'aanya.gupta@example.in', 'India', '2-10', 'marketing ops', 'analytics', 'pending', 'aanya2-ref-' || substr(md5(random()::text), 1, 8), 50, now() - interval '1 day'),
('Advait Patel', 'advait.patel@example.in', 'India', '201-500', 'developer', 'team governance', 'pending', 'advait2-ref-' || substr(md5(random()::text), 1, 8), 75, now() - interval '7 days'),
('Navya Singh', 'navya.singh@example.in', 'India', '11-50', 'marketing', 'QR codes', 'pending', 'navya2-ref-' || substr(md5(random()::text), 1, 8), 54, now() - interval '1 day'),
('Atharv Reddy', 'atharv.reddy@example.in', 'India', '51-200', 'sales', 'all of the above', 'pending', 'atharv2-ref-' || substr(md5(random()::text), 1, 8), 66, now() - interval '5 days'),
('Pari Desai', 'pari.desai@example.in', 'India', '2-10', 'marketing', 'UTM tracking', 'pending', 'pari2-ref-' || substr(md5(random()::text), 1, 8), 52, now() - interval '1 day'),
('Dhruv Kapoor', 'dhruv.kapoor@example.in', 'India', '11-50', 'developer', 'link management', 'pending', 'dhruv2-ref-' || substr(md5(random()::text), 1, 8), 69, now() - interval '6 days'),
('Anaya Iyer', 'anaya.iyer@example.in', 'India', '51-200', 'marketing ops', 'analytics', 'pending', 'anaya2-ref-' || substr(md5(random()::text), 1, 8), 59, now() - interval '2 days'),
('Kabir Kumar', 'kabir.kumar@example.in', 'India', '11-50', 'sales', 'team governance', 'pending', 'kabir2-ref-' || substr(md5(random()::text), 1, 8), 61, now() - interval '3 days'),
('Anushka Menon', 'anushka.menon@example.in', 'India', '2-10', 'marketing', 'QR codes', 'pending', 'anushka2-ref-' || substr(md5(random()::text), 1, 8), 56, now() - interval '2 days'),
('Ayaan Nair', 'ayaan.nair@example.in', 'India', '201-500', 'developer', 'all of the above', 'pending', 'ayaan2-ref-' || substr(md5(random()::text), 1, 8), 73, now() - interval '7 days'),
('Kiara Agarwal', 'kiara.agarwal@example.in', 'India', '11-50', 'marketing', 'UTM tracking', 'pending', 'kiara2-ref-' || substr(md5(random()::text), 1, 8), 53, now() - interval '1 day'),
('Reyansh Joshi', 'reyansh.joshi@example.in', 'India', '51-200', 'sales', 'link management', 'pending', 'reyansh2-ref-' || substr(md5(random()::text), 1, 8), 64, now() - interval '4 days'),
('Saanvi Malhotra', 'saanvi.malhotra@example.in', 'India', '2-10', 'marketing ops', 'analytics', 'pending', 'saanvi2-ref-' || substr(md5(random()::text), 1, 8), 58, now() - interval '2 days'),
('Vivaan Mehta', 'vivaan.mehta@example.in', 'India', '11-50', 'developer', 'team governance', 'pending', 'vivaan2-ref-' || substr(md5(random()::text), 1, 8), 67, now() - interval '5 days'),
('Ira Rao', 'ira.rao@example.in', 'India', '51-200', 'marketing', 'QR codes', 'pending', 'ira2-ref-' || substr(md5(random()::text), 1, 8), 55, now() - interval '1 day'),
('Shaurya Saxena', 'shaurya.saxena@example.in', 'India', '11-50', 'sales', 'all of the above', 'pending', 'shaurya2-ref-' || substr(md5(random()::text), 1, 8), 62, now() - interval '3 days'),
('Nitya Khanna', 'nitya.khanna@example.in', 'India', '2-10', 'marketing', 'UTM tracking', 'pending', 'nitya2-ref-' || substr(md5(random()::text), 1, 8), 51, now() - interval '1 day'),
('Rudra Bose', 'rudra.bose@example.in', 'India', '201-500', 'developer', 'link management', 'pending', 'rudra2-ref-' || substr(md5(random()::text), 1, 8), 74, now() - interval '8 days'),
('Zara Pillai', 'zara.pillai@example.in', 'India', '11-50', 'marketing ops', 'analytics', 'pending', 'zara2-ref-' || substr(md5(random()::text), 1, 8), 60, now() - interval '3 days'),

-- US names (60 records - 30%)
('Sarah Johnson', 'sarah.johnson@example.com', 'United States', '51-200', 'marketing', 'UTM tracking', 'approved', 'sarah-ref-' || substr(md5(random()::text), 1, 8), 92, now() - interval '16 days'),
('Michael Chen', 'michael.chen@example.com', 'United States', '201-500', 'developer', 'all of the above', 'pending', 'michael-ref-' || substr(md5(random()::text), 1, 8), 84, now() - interval '11 days'),
('Emily Rodriguez', 'emily.rodriguez@example.com', 'United States', '11-50', 'marketing', 'link management', 'pending', 'emily-ref-' || substr(md5(random()::text), 1, 8), 81, now() - interval '9 days'),
('David Kim', 'david.kim@example.com', 'United States', '51-200', 'sales', 'analytics', 'approved', 'david-ref-' || substr(md5(random()::text), 1, 8), 90, now() - interval '13 days'),
('Jessica Martinez', 'jessica.martinez@example.com', 'United States', '11-50', 'marketing ops', 'team governance', 'pending', 'jessica-ref-' || substr(md5(random()::text), 1, 8), 77, now() - interval '8 days'),
('Christopher Lee', 'christopher.lee@example.com', 'United States', '201-500', 'developer', 'QR codes', 'pending', 'christopher-ref-' || substr(md5(random()::text), 1, 8), 72, now() - interval '6 days'),
('Amanda Taylor', 'amanda.taylor@example.com', 'United States', '2-10', 'marketing', 'UTM tracking', 'pending', 'amanda-ref-' || substr(md5(random()::text), 1, 8), 68, now() - interval '5 days'),
('Matthew Anderson', 'matthew.anderson@example.com', 'United States', '51-200', 'sales', 'link management', 'pending', 'matthew-ref-' || substr(md5(random()::text), 1, 8), 83, now() - interval '10 days'),
('Ashley Thomas', 'ashley.thomas@example.com', 'United States', '11-50', 'marketing', 'analytics', 'pending', 'ashley-ref-' || substr(md5(random()::text), 1, 8), 65, now() - interval '4 days'),
('Daniel White', 'daniel.white@example.com', 'United States', '201-500', 'developer', 'all of the above', 'approved', 'daniel-ref-' || substr(md5(random()::text), 1, 8), 88, now() - interval '12 days'),
('Jennifer Harris', 'jennifer.harris@example.com', 'United States', '51-200', 'marketing ops', 'team governance', 'pending', 'jennifer-ref-' || substr(md5(random()::text), 1, 8), 70, now() - interval '6 days'),
('Joshua Martin', 'joshua.martin@example.com', 'United States', '11-50', 'sales', 'QR codes', 'pending', 'joshua-ref-' || substr(md5(random()::text), 1, 8), 63, now() - interval '3 days'),
('Melissa Garcia', 'melissa.garcia@example.com', 'United States', '2-10', 'marketing', 'UTM tracking', 'pending', 'melissa-ref-' || substr(md5(random()::text), 1, 8), 59, now() - interval '2 days'),
('Andrew Robinson', 'andrew.robinson@example.com', 'United States', '51-200', 'developer', 'link management', 'pending', 'andrew-ref-' || substr(md5(random()::text), 1, 8), 76, now() - interval '7 days'),
('Stephanie Clark', 'stephanie.clark@example.com', 'United States', '11-50', 'marketing', 'analytics', 'pending', 'stephanie-ref-' || substr(md5(random()::text), 1, 8), 61, now() - interval '3 days'),
('Justin Lewis', 'justin.lewis@example.com', 'United States', '201-500', 'sales', 'team governance', 'pending', 'justin-ref-' || substr(md5(random()::text), 1, 8), 78, now() - interval '8 days'),
('Nicole Walker', 'nicole.walker@example.com', 'United States', '51-200', 'marketing ops', 'QR codes', 'pending', 'nicole-ref-' || substr(md5(random()::text), 1, 8), 66, now() - interval '5 days'),
('Brandon Hall', 'brandon.hall@example.com', 'United States', '11-50', 'developer', 'all of the above', 'pending', 'brandon-ref-' || substr(md5(random()::text), 1, 8), 69, now() - interval '5 days'),
('Rachel Young', 'rachel.young@example.com', 'United States', '2-10', 'marketing', 'UTM tracking', 'pending', 'rachel-ref-' || substr(md5(random()::text), 1, 8), 57, now() - interval '2 days'),
('Ryan Allen', 'ryan.allen@example.com', 'United States', '51-200', 'sales', 'link management', 'approved', 'ryan-ref-' || substr(md5(random()::text), 1, 8), 85, now() - interval '11 days'),
('Lauren King', 'lauren.king@example.com', 'United States', '11-50', 'marketing', 'analytics', 'pending', 'lauren-ref-' || substr(md5(random()::text), 1, 8), 64, now() - interval '4 days'),
('Kevin Wright', 'kevin.wright@example.com', 'United States', '201-500', 'developer', 'team governance', 'pending', 'kevin-ref-' || substr(md5(random()::text), 1, 8), 71, now() - interval '6 days'),
('Samantha Scott', 'samantha.scott@example.com', 'United States', '51-200', 'marketing ops', 'QR codes', 'pending', 'samantha-ref-' || substr(md5(random()::text), 1, 8), 58, now() - interval '2 days'),
('Eric Green', 'eric.green@example.com', 'United States', '11-50', 'sales', 'all of the above', 'pending', 'eric-ref-' || substr(md5(random()::text), 1, 8), 62, now() - interval '3 days'),
('Brittany Adams', 'brittany.adams@example.com', 'United States', '2-10', 'marketing', 'UTM tracking', 'pending', 'brittany-ref-' || substr(md5(random()::text), 1, 8), 54, now() - interval '1 day'),
('Tyler Baker', 'tyler.baker@example.com', 'United States', '51-200', 'developer', 'link management', 'pending', 'tyler-ref-' || substr(md5(random()::text), 1, 8), 67, now() - interval '5 days'),
('Megan Gonzalez', 'megan.gonzalez@example.com', 'United States', '11-50', 'marketing', 'analytics', 'pending', 'megan-ref-' || substr(md5(random()::text), 1, 8), 60, now() - interval '3 days'),
('Jonathan Nelson', 'jonathan.nelson@example.com', 'United States', '201-500', 'sales', 'team governance', 'pending', 'jonathan-ref-' || substr(md5(random()::text), 1, 8), 73, now() - interval '7 days'),
('Heather Carter', 'heather.carter@example.com', 'United States', '51-200', 'marketing ops', 'QR codes', 'pending', 'heather-ref-' || substr(md5(random()::text), 1, 8), 56, now() - interval '2 days'),
('Nicholas Mitchell', 'nicholas.mitchell@example.com', 'United States', '11-50', 'developer', 'all of the above', 'approved', 'nicholas-ref-' || substr(md5(random()::text), 1, 8), 86, now() - interval '10 days'),
('Kimberly Perez', 'kimberly.perez@example.com', 'United States', '2-10', 'marketing', 'UTM tracking', 'pending', 'kimberly-ref-' || substr(md5(random()::text), 1, 8), 53, now() - interval '1 day'),
('Jacob Roberts', 'jacob.roberts@example.com', 'United States', '51-200', 'sales', 'link management', 'pending', 'jacob-ref-' || substr(md5(random()::text), 1, 8), 65, now() - interval '4 days'),
('Rebecca Turner', 'rebecca.turner@example.com', 'United States', '11-50', 'marketing', 'analytics', 'pending', 'rebecca-ref-' || substr(md5(random()::text), 1, 8), 59, now() - interval '2 days'),
('Austin Phillips', 'austin.phillips@example.com', 'United States', '201-500', 'developer', 'team governance', 'pending', 'austin-ref-' || substr(md5(random()::text), 1, 8), 70, now() - interval '6 days'),
('Katherine Campbell', 'katherine.campbell@example.com', 'United States', '51-200', 'marketing ops', 'QR codes', 'pending', 'katherine-ref-' || substr(md5(random()::text), 1, 8), 57, now() - interval '2 days'),
('Zachary Parker', 'zachary.parker@example.com', 'United States', '11-50', 'sales', 'all of the above', 'pending', 'zachary-ref-' || substr(md5(random()::text), 1, 8), 63, now() - interval '4 days'),
('Natalie Evans', 'natalie.evans@example.com', 'United States', '2-10', 'marketing', 'UTM tracking', 'pending', 'natalie-ref-' || substr(md5(random()::text), 1, 8), 52, now() - interval '1 day'),
('Benjamin Edwards', 'benjamin.edwards@example.com', 'United States', '51-200', 'developer', 'link management', 'pending', 'benjamin-ref-' || substr(md5(random()::text), 1, 8), 68, now() - interval '5 days'),
('Victoria Collins', 'victoria.collins@example.com', 'United States', '11-50', 'marketing', 'analytics', 'pending', 'victoria-ref-' || substr(md5(random()::text), 1, 8), 60, now() - interval '3 days'),
('Alexander Stewart', 'alexander.stewart@example.com', 'United States', '201-500', 'sales', 'team governance', 'pending', 'alexander-ref-' || substr(md5(random()::text), 1, 8), 72, now() - interval '7 days'),
('Christina Sanchez', 'christina.sanchez@example.com', 'United States', '51-200', 'marketing ops', 'QR codes', 'pending', 'christina-ref-' || substr(md5(random()::text), 1, 8), 55, now() - interval '1 day'),
('Nathan Morris', 'nathan.morris@example.com', 'United States', '11-50', 'developer', 'all of the above', 'pending', 'nathan-ref-' || substr(md5(random()::text), 1, 8), 66, now() - interval '5 days'),
('Michelle Rogers', 'michelle.rogers@example.com', 'United States', '2-10', 'marketing', 'UTM tracking', 'pending', 'michelle-ref-' || substr(md5(random()::text), 1, 8), 51, now() - interval '1 day'),
('Ethan Reed', 'ethan.reed@example.com', 'United States', '51-200', 'sales', 'link management', 'pending', 'ethan-ref-' || substr(md5(random()::text), 1, 8), 64, now() - interval '4 days'),
('Danielle Cook', 'danielle.cook@example.com', 'United States', '11-50', 'marketing', 'analytics', 'pending', 'danielle-ref-' || substr(md5(random()::text), 1, 8), 58, now() - interval '2 days'),
('Samuel Morgan', 'samuel.morgan@example.com', 'United States', '201-500', 'developer', 'team governance', 'pending', 'samuel-ref-' || substr(md5(random()::text), 1, 8), 69, now() - interval '6 days'),
('Olivia Bell', 'olivia.bell@example.com', 'United States', '51-200', 'marketing ops', 'QR codes', 'pending', 'olivia-ref-' || substr(md5(random()::text), 1, 8), 56, now() - interval '2 days'),
('Christian Murphy', 'christian.murphy@example.com', 'United States', '11-50', 'sales', 'all of the above', 'pending', 'christian-ref-' || substr(md5(random()::text), 1, 8), 62, now() - interval '3 days'),
('Amber Bailey', 'amber.bailey@example.com', 'United States', '2-10', 'marketing', 'UTM tracking', 'pending', 'amber-ref-' || substr(md5(random()::text), 1, 8), 50, now() - interval '1 day'),
('Dylan Rivera', 'dylan.rivera@example.com', 'United States', '51-200', 'developer', 'link management', 'approved', 'dylan-ref-' || substr(md5(random()::text), 1, 8), 84, now() - interval '9 days'),
('Courtney Cooper', 'courtney.cooper@example.com', 'United States', '11-50', 'marketing', 'analytics', 'pending', 'courtney-ref-' || substr(md5(random()::text), 1, 8), 59, now() - interval '2 days'),
('Jordan Richardson', 'jordan.richardson@example.com', 'United States', '201-500', 'sales', 'team governance', 'pending', 'jordan-ref-' || substr(md5(random()::text), 1, 8), 71, now() - interval '6 days'),
('Alexis Cox', 'alexis.cox@example.com', 'United States', '51-200', 'marketing ops', 'QR codes', 'pending', 'alexis-ref-' || substr(md5(random()::text), 1, 8), 54, now() - interval '1 day'),
('Cameron Howard', 'cameron.howard@example.com', 'United States', '11-50', 'developer', 'all of the above', 'pending', 'cameron-ref-' || substr(md5(random()::text), 1, 8), 67, now() - interval '5 days'),
('Morgan Ward', 'morgan.ward@example.com', 'United States', '2-10', 'marketing', 'UTM tracking', 'pending', 'morgan-ref-' || substr(md5(random()::text), 1, 8), 53, now() - interval '1 day'),
('Taylor Torres', 'taylor.torres@example.com', 'United States', '51-200', 'sales', 'link management', 'pending', 'taylor-ref-' || substr(md5(random()::text), 1, 8), 63, now() - interval '4 days'),
('Casey Peterson', 'casey.peterson@example.com', 'United States', '11-50', 'marketing', 'analytics', 'pending', 'casey-ref-' || substr(md5(random()::text), 1, 8), 57, now() - interval '2 days'),
('Riley Gray', 'riley.gray@example.com', 'United States', '201-500', 'developer', 'team governance', 'pending', 'riley-ref-' || substr(md5(random()::text), 1, 8), 68, now() - interval '5 days'),
('Avery Ramirez', 'avery.ramirez@example.com', 'United States', '51-200', 'marketing ops', 'QR codes', 'pending', 'avery-ref-' || substr(md5(random()::text), 1, 8), 55, now() - interval '1 day'),

-- European names (40 records - 20%)
('Emma Müller', 'emma.muller@example.de', 'Germany', '51-200', 'marketing', 'UTM tracking', 'approved', 'emma-ref-' || substr(md5(random()::text), 1, 8), 89, now() - interval '12 days'),
('Pierre Dubois', 'pierre.dubois@example.fr', 'France', '11-50', 'developer', 'all of the above', 'pending', 'pierre-ref-' || substr(md5(random()::text), 1, 8), 79, now() - interval '9 days'),
('Sofia Garcia', 'sofia.garcia@example.es', 'Spain', '51-200', 'sales', 'link management', 'pending', 'sofia-ref-' || substr(md5(random()::text), 1, 8), 74, now() - interval '7 days'),
('Lucas Schmidt', 'lucas.schmidt@example.de', 'Germany', '201-500', 'marketing ops', 'analytics', 'pending', 'lucas-ref-' || substr(md5(random()::text), 1, 8), 81, now() - interval '10 days'),
('Camille Martin', 'camille.martin@example.fr', 'France', '11-50', 'marketing', 'team governance', 'pending', 'camille-ref-' || substr(md5(random()::text), 1, 8), 66, now() - interval '5 days'),
('Marco Rossi', 'marco.rossi@example.it', 'Italy', '51-200', 'developer', 'QR codes', 'approved', 'marco-ref-' || substr(md5(random()::text), 1, 8), 87, now() - interval '11 days'),
('Anna Kowalski', 'anna.kowalski@example.pl', 'Poland', '2-10', 'sales', 'UTM tracking', 'pending', 'anna-ref-' || substr(md5(random()::text), 1, 8), 62, now() - interval '3 days'),
('Oliver Berg', 'oliver.berg@example.se', 'Sweden', '11-50', 'marketing', 'link management', 'pending', 'oliver-ref-' || substr(md5(random()::text), 1, 8), 69, now() - interval '6 days'),
('Elena Petrov', 'elena.petrov@example.ru', 'Russia', '51-200', 'developer', 'analytics', 'pending', 'elena-ref-' || substr(md5(random()::text), 1, 8), 71, now() - interval '7 days'),
('Henrik Nielsen', 'henrik.nielsen@example.dk', 'Denmark', '11-50', 'marketing ops', 'team governance', 'pending', 'henrik-ref-' || substr(md5(random()::text), 1, 8), 58, now() - interval '2 days'),
('Isabella Romano', 'isabella.romano@example.it', 'Italy', '201-500', 'sales', 'QR codes', 'pending', 'isabella-ref-' || substr(md5(random()::text), 1, 8), 75, now() - interval '8 days'),
('Maximilian Weber', 'max.weber@example.de', 'Germany', '51-200', 'developer', 'all of the above', 'pending', 'max-ref-' || substr(md5(random()::text), 1, 8), 67, now() - interval '5 days'),
('Amelie Leroy', 'amelie.leroy@example.fr', 'France', '11-50', 'marketing', 'UTM tracking', 'pending', 'amelie-ref-' || substr(md5(random()::text), 1, 8), 60, now() - interval '3 days'),
('Carlos Fernandez', 'carlos.fernandez@example.es', 'Spain', '2-10', 'sales', 'link management', 'pending', 'carlos-ref-' || substr(md5(random()::text), 1, 8), 63, now() - interval '4 days'),
('Lena Wagner', 'lena.wagner@example.de', 'Germany', '51-200', 'marketing ops', 'analytics', 'pending', 'lena-ref-' || substr(md5(random()::text), 1, 8), 56, now() - interval '2 days'),
('Thomas Bernard', 'thomas.bernard@example.fr', 'France', '11-50', 'developer', 'team governance', 'pending', 'thomas-ref-' || substr(md5(random()::text), 1, 8), 70, now() - interval '6 days'),
('Giulia Ferrari', 'giulia.ferrari@example.it', 'Italy', '51-200', 'marketing', 'QR codes', 'pending', 'giulia-ref-' || substr(md5(random()::text), 1, 8), 64, now() - interval '4 days'),
('Jan Andersson', 'jan.andersson@example.se', 'Sweden', '11-50', 'sales', 'all of the above', 'pending', 'jan-ref-' || substr(md5(random()::text), 1, 8), 59, now() - interval '2 days'),
('Katarina Novak', 'katarina.novak@example.cz', 'Czech Republic', '201-500', 'developer', 'UTM tracking', 'approved', 'katarina-ref-' || substr(md5(random()::text), 1, 8), 83, now() - interval '10 days'),
('Nikolai Ivanov', 'nikolai.ivanov@example.ru', 'Russia', '51-200', 'marketing ops', 'link management', 'pending', 'nikolai-ref-' || substr(md5(random()::text), 1, 8), 61, now() - interval '3 days'),
('Freya Hansen', 'freya.hansen@example.dk', 'Denmark', '11-50', 'marketing', 'analytics', 'pending', 'freya-ref-' || substr(md5(random()::text), 1, 8), 57, now() - interval '2 days'),
('Federico Bianchi', 'federico.bianchi@example.it', 'Italy', '2-10', 'sales', 'team governance', 'pending', 'federico-ref-' || substr(md5(random()::text), 1, 8), 65, now() - interval '4 days'),
('Felix Hoffmann', 'felix.hoffmann@example.de', 'Germany', '51-200', 'developer', 'QR codes', 'pending', 'felix-ref-' || substr(md5(random()::text), 1, 8), 68, now() - interval '5 days'),
('Juliette Moreau', 'juliette.moreau@example.fr', 'France', '11-50', 'marketing', 'all of the above', 'pending', 'juliette-ref-' || substr(md5(random()::text), 1, 8), 54, now() - interval '1 day'),
('Diego Lopez', 'diego.lopez@example.es', 'Spain', '51-200', 'sales', 'UTM tracking', 'pending', 'diego-ref-' || substr(md5(random()::text), 1, 8), 62, now() - interval '3 days'),
('Mia Fischer', 'mia.fischer@example.de', 'Germany', '11-50', 'developer', 'link management', 'pending', 'mia-ref-' || substr(md5(random()::text), 1, 8), 66, now() - interval '5 days'),
('Louis Girard', 'louis.girard@example.fr', 'France', '201-500', 'marketing ops', 'analytics', 'pending', 'louis-ref-' || substr(md5(random()::text), 1, 8), 72, now() - interval '7 days'),
('Chiara Conti', 'chiara.conti@example.it', 'Italy', '51-200', 'marketing', 'team governance', 'pending', 'chiara-ref-' || substr(md5(random()::text), 1, 8), 58, now() - interval '2 days'),
('Erik Larsson', 'erik.larsson@example.se', 'Sweden', '11-50', 'sales', 'QR codes', 'pending', 'erik-ref-' || substr(md5(random()::text), 1, 8), 60, now() - interval '3 days'),
('Petra Svoboda', 'petra.svoboda@example.cz', 'Czech Republic', '2-10', 'developer', 'all of the above', 'pending', 'petra-ref-' || substr(md5(random()::text), 1, 8), 63, now() - interval '4 days'),
('Dmitry Sokolov', 'dmitry.sokolov@example.ru', 'Russia', '51-200', 'marketing', 'UTM tracking', 'pending', 'dmitry-ref-' || substr(md5(random()::text), 1, 8), 55, now() - interval '1 day'),
('Astrid Johansen', 'astrid.johansen@example.dk', 'Denmark', '11-50', 'sales', 'link management', 'pending', 'astrid-ref-' || substr(md5(random()::text), 1, 8), 64, now() - interval '4 days'),
('Alessandro Gallo', 'alessandro.gallo@example.it', 'Italy', '51-200', 'developer', 'analytics', 'pending', 'alessandro-ref-' || substr(md5(random()::text), 1, 8), 67, now() - interval '5 days'),
('Hannah Klein', 'hannah.klein@example.de', 'Germany', '11-50', 'marketing ops', 'team governance', 'pending', 'hannah-ref-' || substr(md5(random()::text), 1, 8), 56, now() - interval '2 days'),
('Antoine Rousseau', 'antoine.rousseau@example.fr', 'France', '201-500', 'sales', 'QR codes', 'pending', 'antoine-ref-' || substr(md5(random()::text), 1, 8), 69, now() - interval '6 days'),
('Lucia Martinez', 'lucia.martinez@example.es', 'Spain', '51-200', 'marketing', 'all of the above', 'pending', 'lucia-ref-' || substr(md5(random()::text), 1, 8), 61, now() - interval '3 days'),
('Jonas Lindberg', 'jonas.lindberg@example.se', 'Sweden', '11-50', 'developer', 'UTM tracking', 'pending', 'jonas-ref-' || substr(md5(random()::text), 1, 8), 59, now() - interval '2 days'),
('Vera Novakova', 'vera.novakova@example.cz', 'Czech Republic', '2-10', 'sales', 'link management', 'pending', 'vera-ref-' || substr(md5(random()::text), 1, 8), 53, now() - interval '1 day'),
('Anton Volkov', 'anton.volkov@example.ru', 'Russia', '51-200', 'marketing', 'analytics', 'pending', 'anton-ref-' || substr(md5(random()::text), 1, 8), 65, now() - interval '4 days'),
('Sofie Olsen', 'sofie.olsen@example.dk', 'Denmark', '11-50', 'developer', 'team governance', 'pending', 'sofie-ref-' || substr(md5(random()::text), 1, 8), 57, now() - interval '2 days'),

-- Other regions (30 records - 15%)
('Yuki Tanaka', 'yuki.tanaka@example.jp', 'Japan', '51-200', 'marketing', 'UTM tracking', 'pending', 'yuki-ref-' || substr(md5(random()::text), 1, 8), 76, now() - interval '8 days'),
('Wei Zhang', 'wei.zhang@example.cn', 'China', '201-500', 'developer', 'all of the above', 'pending', 'wei-ref-' || substr(md5(random()::text), 1, 8), 80, now() - interval '9 days'),
('Gabriel Silva', 'gabriel.silva@example.br', 'Brazil', '11-50', 'sales', 'link management', 'pending', 'gabriel-ref-' || substr(md5(random()::text), 1, 8), 68, now() - interval '5 days'),
('Fatima Al-Rashid', 'fatima.alrashid@example.ae', 'United Arab Emirates', '51-200', 'marketing ops', 'analytics', 'approved', 'fatima-ref-' || substr(md5(random()::text), 1, 8), 84, now() - interval '10 days'),
('James Wilson', 'james.wilson@example.au', 'Australia', '11-50', 'marketing', 'team governance', 'pending', 'james-ref-' || substr(md5(random()::text), 1, 8), 63, now() - interval '4 days'),
('Hiroshi Sato', 'hiroshi.sato@example.jp', 'Japan', '51-200', 'developer', 'QR codes', 'pending', 'hiroshi-ref-' || substr(md5(random()::text), 1, 8), 70, now() - interval '6 days'),
('Li Chen', 'li.chen@example.cn', 'China', '201-500', 'sales', 'UTM tracking', 'pending', 'li-ref-' || substr(md5(random()::text), 1, 8), 73, now() - interval '7 days'),
('Isabela Santos', 'isabela.santos@example.br', 'Brazil', '11-50', 'marketing', 'link management', 'pending', 'isabela-ref-' || substr(md5(random()::text), 1, 8), 59, now() - interval '2 days'),
('Ahmed Hassan', 'ahmed.hassan@example.ae', 'United Arab Emirates', '2-10', 'developer', 'analytics', 'pending', 'ahmed-ref-' || substr(md5(random()::text), 1, 8), 65, now() - interval '4 days'),
('Emily Thompson', 'emily.thompson@example.au', 'Australia', '51-200', 'marketing ops', 'team governance', 'pending', 'emily2-ref-' || substr(md5(random()::text), 1, 8), 61, now() - interval '3 days'),
('Kenji Yamamoto', 'kenji.yamamoto@example.jp', 'Japan', '11-50', 'sales', 'QR codes', 'pending', 'kenji-ref-' || substr(md5(random()::text), 1, 8), 66, now() - interval '5 days'),
('Jing Wang', 'jing.wang@example.cn', 'China', '51-200', 'marketing', 'all of the above', 'pending', 'jing-ref-' || substr(md5(random()::text), 1, 8), 69, now() - interval '6 days'),
('Rafael Costa', 'rafael.costa@example.br', 'Brazil', '11-50', 'developer', 'UTM tracking', 'pending', 'rafael-ref-' || substr(md5(random()::text), 1, 8), 57, now() - interval '2 days'),
('Layla Mohammed', 'layla.mohammed@example.ae', 'United Arab Emirates', '201-500', 'sales', 'link management', 'pending', 'layla-ref-' || substr(md5(random()::text), 1, 8), 72, now() - interval '7 days'),
('Liam Brown', 'liam.brown@example.au', 'Australia', '51-200', 'marketing', 'analytics', 'pending', 'liam-ref-' || substr(md5(random()::text), 1, 8), 60, now() - interval '3 days'),
('Sakura Suzuki', 'sakura.suzuki@example.jp', 'Japan', '11-50', 'developer', 'team governance', 'pending', 'sakura-ref-' || substr(md5(random()::text), 1, 8), 64, now() - interval '4 days'),
('Xiaoming Liu', 'xiaoming.liu@example.cn', 'China', '2-10', 'marketing ops', 'QR codes', 'pending', 'xiaoming-ref-' || substr(md5(random()::text), 1, 8), 58, now() - interval '2 days'),
('Lucas Oliveira', 'lucas.oliveira@example.br', 'Brazil', '51-200', 'sales', 'all of the above', 'pending', 'lucas2-ref-' || substr(md5(random()::text), 1, 8), 67, now() - interval '5 days'),
('Omar Khalil', 'omar.khalil@example.ae', 'United Arab Emirates', '11-50', 'marketing', 'UTM tracking', 'pending', 'omar-ref-' || substr(md5(random()::text), 1, 8), 55, now() - interval '1 day'),
('Olivia Smith', 'olivia.smith@example.au', 'Australia', '51-200', 'developer', 'link management', 'pending', 'olivia2-ref-' || substr(md5(random()::text), 1, 8), 62, now() - interval '3 days'),
('Takeshi Kobayashi', 'takeshi.kobayashi@example.jp', 'Japan', '11-50', 'sales', 'analytics', 'pending', 'takeshi-ref-' || substr(md5(random()::text), 1, 8), 59, now() - interval '2 days'),
('Ming Zhao', 'ming.zhao@example.cn', 'China', '201-500', 'marketing', 'team governance', 'pending', 'ming-ref-' || substr(md5(random()::text), 1, 8), 71, now() - interval '6 days'),
('Bianca Almeida', 'bianca.almeida@example.br', 'Brazil', '51-200', 'developer', 'QR codes', 'pending', 'bianca-ref-' || substr(md5(random()::text), 1, 8), 56, now() - interval '2 days'),
('Yasmin Ali', 'yasmin.ali@example.ae', 'United Arab Emirates', '11-50', 'marketing ops', 'all of the above', 'pending', 'yasmin-ref-' || substr(md5(random()::text), 1, 8), 63, now() - interval '4 days'),
('Noah Davis', 'noah.davis@example.au', 'Australia', '2-10', 'sales', 'UTM tracking', 'pending', 'noah-ref-' || substr(md5(random()::text), 1, 8), 54, now() - interval '1 day'),
('Aiko Nakamura', 'aiko.nakamura@example.jp', 'Japan', '51-200', 'marketing', 'link management', 'pending', 'aiko-ref-' || substr(md5(random()::text), 1, 8), 65, now() - interval '4 days'),
('Yun Li', 'yun.li@example.cn', 'China', '11-50', 'developer', 'analytics', 'pending', 'yun-ref-' || substr(md5(random()::text), 1, 8), 60, now() - interval '3 days'),
('Matheus Ferreira', 'matheus.ferreira@example.br', 'Brazil', '51-200', 'sales', 'team governance', 'pending', 'matheus-ref-' || substr(md5(random()::text), 1, 8), 58, now() - interval '2 days'),
('Zahra Ibrahim', 'zahra.ibrahim@example.ae', 'United Arab Emirates', '11-50', 'marketing', 'QR codes', 'pending', 'zahra-ref-' || substr(md5(random()::text), 1, 8), 61, now() - interval '3 days'),
('Ava Johnson', 'ava.johnson@example.au', 'Australia', '201-500', 'developer', 'all of the above', 'pending', 'ava-ref-' || substr(md5(random()::text), 1, 8), 68, now() - interval '5 days');